[package]
name = "variant_access"
version = "0.1.0"
authors = ["Jacob Turner <jacob@friendrat.com> "]
edition = "2018"
readme = "README.md"
repository = "https://github.com/FriendRat/variant_access"
license = "MIT"
categories = ["development-tools", "rust-patterns"]
build = false

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
variant_access_traits = {path = "variant_access_traits"}
variant_access_derive = {path = "variant_access_derive"}