[package]
name = "variant_access_derive"
version = "0.1.0"
authors = ["Jacob Turner"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
variant_access_traits = {path = "../variant_access_traits"}